export const artList = [
  {
    fileName: "moonlight1.jpg",
    artName: "And I Wake Up Falling",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight2.png",
    artName: "Cover",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight3.png",
    artName: "Dance of the Dove",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight4.png",
    artName: "Delicate Angel",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight5.png",
    artName: "Disbelief",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight6.jpg",
    artName: "Entangled Emotions",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight7.jpg",
    artName: "Follow Me",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight8.jpg",
    artName: "Oasis",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight9.jpg",
    artName: "Rosalia",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight10.jpg",
    artName: "Soar",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight11.jpg",
    artName: "Song of the Nightingale",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "moonlight12.png",
    artName: "The Beautiful Question",
    artist: "Moonlight",
    artistUrl: "https://www.instagram.com/moonlightkcreations/",
  },
  {
    fileName: "ashley.jpg",
    artName: "Warrior",
    artist: "Ashley Shaw",
    artistUrl: "https://www.instagram.com/tbg_art/",
  },
  {
    fileName: "our-playful-hero.jpg",
    artName: "Our Playful Hero",
    artist: "unknown",
    artistUrl: "https://www.rosalianightsong.com",
  },
  {
    fileName: "between-the-raindrops.jpg",
    artName: "Between the Raindrops",
    artist: "unknown",
    artistUrl: "https://www.rosalianightsong.com",
  },
  {
    fileName: "sunday-best.jpg",
    artName: "Sunday Best",
    artist: "unknown",
    artistUrl: "https://www.rosalianightsong.com",
  },
  {
    fileName: "will-of-the-heart.jpg",
    artName: "Will of the Heart",
    artist: "unknown",
    artistUrl: "https://www.rosalianightsong.com",
  },
  {
    fileName: "untitled.jpg",
    artName: "Divine Elegance",
    artist: "unknown",
    artistUrl: "https://www.rosalianightsong.com",
  },
  {
    fileName: "gateway-of-roses.jpg",
    artName: "Gateway of Roses",
    artist: "unknown",
    artistUrl: "https://www.rosalianightsong.com",
  },
  {
    fileName: "untitled2.jpg",
    artName: "Swift Justice",
    artist: "unknown",
    artistUrl: "https://www.rosalianightsong.com",
  },
  {
    fileName: "untitled3.jpg",
    artName: "The Sweetest Smile",
    artist: "unknown",
    artistUrl: "https://www.rosalianightsong.com",
  },
  {
    fileName: "lena_smith11.jpg",
    artName: "A Night on the Town",
    artist: "Lena",
    artistUrl: "https://www.twitter.com/lena_smith11/",
  },
];
